//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COTES.ISTOK.ASC.Audit
{
    using System;
    using System.Collections.Generic;
    
    [System.Serializable]
    [System.Runtime.Serialization.DataContract]
    
    public partial class AuditType
    {
    	[System.Runtime.Serialization.DataMember]
        public int ID { get; private set; }
    	[System.Runtime.Serialization.DataMember]
        private int EntryID { get; set; }
    	[System.Runtime.Serialization.DataMember]
        public int TypeID { get; set; }
    	[System.Runtime.Serialization.DataMember]
        protected byte[] ExtGuidBinary { get; set; }
    	[System.Runtime.Serialization.DataMember]
        public string TypeNameOld { get; set; }
    	[System.Runtime.Serialization.DataMember]
        public string TypeNameNew { get; set; }
    	[System.Runtime.Serialization.DataMember]
        public string TypePropsOld { get; set; }
    	[System.Runtime.Serialization.DataMember]
        public string TypePropsNew { get; set; }
    	[System.Runtime.Serialization.DataMember]
        public byte[] TypeImageOld { get; set; }
    	[System.Runtime.Serialization.DataMember]
        public byte[] TypeImageNew { get; set; }
    	[System.Runtime.Serialization.DataMember]
        public string TypeChildFilterOld { get; set; }
    	[System.Runtime.Serialization.DataMember]
        public string TypeChildFilterNew { get; set; }
    
    	[System.Runtime.Serialization.DataMember]
        public virtual AuditEntry AuditEntry { get; set; }
    }
}
