//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COTES.ISTOK.ASC.Audit
{
    using System;
    using System.Collections.Generic;
    
    [System.Serializable]
    [System.Runtime.Serialization.DataContract]
    
    public partial class AuditGroup
    {
    	[System.Runtime.Serialization.DataMember]
        public int ID { get; private set; }
    	[System.Runtime.Serialization.DataMember]
        private int EntryID { get; set; }
    	[System.Runtime.Serialization.DataMember]
        public int GroupID { get; set; }
    	[System.Runtime.Serialization.DataMember]
        public string GroupNameOld { get; set; }
    	[System.Runtime.Serialization.DataMember]
        public string GroupNameNew { get; set; }
    	[System.Runtime.Serialization.DataMember]
        public string GroupDescriptionOld { get; set; }
    	[System.Runtime.Serialization.DataMember]
        public string GroupDescriptionNew { get; set; }
    
    	[System.Runtime.Serialization.DataMember]
        public virtual AuditEntry AuditEntry { get; set; }
    }
}
