//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COTES.ISTOK.ASC.Audit
{
    using System;
    using System.Collections.Generic;
    
    [System.Serializable]
    [System.Runtime.Serialization.DataContract(IsReference = true)]
    
    public partial class AuditEntry
    {
        public AuditEntry()
        {
            this.AuditLobs = new HashSet<AuditLob>();
            this.AuditProps = new HashSet<AuditProp>();
            this.AuditUnits = new HashSet<AuditUnit>();
            this.AuditCalcStarts = new HashSet<AuditCalcStart>();
            this.AuditValues = new HashSet<AuditValue>();
            this.AuditGroups = new HashSet<AuditGroup>();
            this.AuditTypes = new HashSet<AuditType>();
            this.AuditUsers = new HashSet<AuditUser>();
        }
    
    	[System.Runtime.Serialization.DataMember]
        public int ID { get; private set; }
    	[System.Runtime.Serialization.DataMember]
        public System.DateTime Time { get; set; }
    	[System.Runtime.Serialization.DataMember]
        public string UserLogin { get; set; }
    	[System.Runtime.Serialization.DataMember]
        public string UserFullName { get; set; }
    	[System.Runtime.Serialization.DataMember]
        public string UserPosition { get; set; }
    	[System.Runtime.Serialization.DataMember]
        public string UserRole { get; set; }
    
    	[System.Runtime.Serialization.DataMember]
        public virtual HashSet<AuditLob> AuditLobs { get; private set; }
    	[System.Runtime.Serialization.DataMember]
        public virtual HashSet<AuditProp> AuditProps { get; private set; }
    	[System.Runtime.Serialization.DataMember]
        public virtual HashSet<AuditUnit> AuditUnits { get; private set; }
    	[System.Runtime.Serialization.DataMember]
        public virtual HashSet<AuditCalcStart> AuditCalcStarts { get; set; }
    	[System.Runtime.Serialization.DataMember]
        public virtual HashSet<AuditValue> AuditValues { get; set; }
    	[System.Runtime.Serialization.DataMember]
        public virtual HashSet<AuditGroup> AuditGroups { get; set; }
    	[System.Runtime.Serialization.DataMember]
        public virtual HashSet<AuditType> AuditTypes { get; set; }
    	[System.Runtime.Serialization.DataMember]
        public virtual HashSet<AuditUser> AuditUsers { get; set; }
    }
}
