//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COTES.ISTOK.ASC.Audit
{
    using System;
    using System.Collections.Generic;
    
    [System.Serializable]
    [System.Runtime.Serialization.DataContract]
    
    public partial class AuditProp
    {
    	[System.Runtime.Serialization.DataMember]
        public int ID { get; private set; }
    	[System.Runtime.Serialization.DataMember]
        private int EntryID { get; set; }
    	[System.Runtime.Serialization.DataMember]
        public int UnitNodeID { get; set; }
    	[System.Runtime.Serialization.DataMember]
        public string UnitNodeFullPath { get; set; }
    	[System.Runtime.Serialization.DataMember]
        public string PropName { get; set; }
    	[System.Runtime.Serialization.DataMember]
        public Nullable<int> RevisionID { get; set; }
    	[System.Runtime.Serialization.DataMember]
        public Nullable<System.DateTime> RevisionTime { get; set; }
    	[System.Runtime.Serialization.DataMember]
        public string RevisionBrief { get; set; }
    	[System.Runtime.Serialization.DataMember]
        public string ValueOld { get; set; }
    	[System.Runtime.Serialization.DataMember]
        public string ValueNew { get; set; }
    
    	[System.Runtime.Serialization.DataMember]
        public virtual AuditEntry AuditEntry { get; set; }
    }
}
