//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient {
    
    
    public partial class TreeTemplate {
        
        /// <summary>
        /// TreeViewPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel TreeViewPanel;
        
        /// <summary>
        /// TreeViewStructure control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TreeView TreeViewStructure;
        
        /// <summary>
        /// TreeContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder TreeContent;

        /// <summary>
        /// UnitPropertiesView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebClient.PropertiesView UnitPropertiesView;

        protected global::System.Web.UI.WebControls.Label ObjectInformLabel;

        protected global::AjaxControlToolkit.TabContainer Tabs;
        protected global::AjaxControlToolkit.TabPanel PropertyViewTab;
        protected global::AjaxControlToolkit.TabPanel ContentTab;
    }
}
