//
//  This CSharp output file generated by Gardens Point LEX
//  Version:  1.0.1.250 (2009-01-01)
//  Machine:  DMDEVICE
//  DateTime: 28.07.2011 13:58:32
//  UserName: kolchin
//  GPLEX input file <TepScanner.l>
//  GPLEX frame file <D:\kody\VSSolutions\GPParser\gplexx.frame>
//
//  Option settings: unicode, parser, minimize, classes, compressmap, compressnext
//  Fallback code page: utf-8
//

//
// gplexx.frame
// Version 1.0.0 of 01-November-2008
//
#define BACKUP

using System;
using System.IO;
using System.Text;
using System.Collections.Generic;
#if !STANDALONE
using gppg;
#endif
//using COTES.ISTOK.ASC;

namespace COTES.ISTOK.Calc
{   
    /// <summary>
    /// Summary Canonical example of GPLEX automaton
    /// </summary>
    
#if STANDALONE
    //
    // These are the dummy declarations for stand-alone GPLEX applications
    // normally these declarations would come from the parser.
    // If you declare /noparser, or %option noparser then you get this.
    //

    public enum Tokens
    { 
      EOF = 0, maxParseToken = int.MaxValue 
      // must have at least these two, values are almost arbitrary
    }

    public abstract class ScanBase
    {
        public abstract int yylex();
        protected virtual bool yywrap() { return true; }
#if BABEL
        protected abstract int CurrentSc { get; set; }
        // EolState is the 32-bit of state data persisted at 
        // the end of each line for Visual Studio colorization.  
        // The default is to return CurrentSc.  You must override
        // this if you want more complicated behavior.
        public virtual int EolState { 
            get { return CurrentSc; }
            set { CurrentSc = value; } 
        }
    }
    
    public interface IColorScan
    {
        void SetSource(string source, int offset);
        int GetNext(ref int state, out int start, out int end);
#endif // BABEL
    }

#endif // STANDALONE

    public abstract class ScanBuff
    {
        public const int EOF = -1;
        public abstract int Pos { get; set; }
        public abstract int Read();
        public abstract int Peek();
        public abstract int ReadPos { get; }
        public abstract string GetString(int b, int e);
        
        public const int UnicodeReplacementChar = 0xFFFD;
    }
    
    // If the compiler can't find ScanBase maybe you need to run
    // GPPG with the /gplex option, or GPLEX with /noparser
#if BABEL
    public sealed partial class Scanner : ScanBase, IColorScan
    {
        public ScanBuff buffer;
        int currentScOrd = 0;  // start condition ordinal
        
        protected override int CurrentSc 
        {
             // The current start state is a property
             // to try to avoid the user error of setting
             // scState but forgetting to update the FSA
             // start state "currentStart"
             //
             get { return currentScOrd; }  // i.e. return YY_START;
             set { currentScOrd = value;   // i.e. BEGIN(value);
                   currentStart = startState[value]; }
        }
#else  // BABEL
    public sealed partial class Scanner : ScanBase
    {
        public ScanBuff buffer;
        int currentScOrd = 0;  // start condition ordinal
#endif // BABEL
        
        private static int GetMaxParseToken() {
            System.Reflection.FieldInfo f = typeof(Tokens).GetField("maxParseToken");
            return (f == null ? int.MaxValue : (int)f.GetValue(null));
        }
        
        static int parserMax = GetMaxParseToken();
        
        enum Result {accept, noMatch, contextFound};

        const int maxAccept = 110;
        const int initial = 111;
        const int eofNum = 0;
        const int goStart = -1;
        const int INITIAL = 0;

#region user code
/*
// ÐÐ¸ÑÐµÑÐ°Ð»Ñ //////////////////////////////////////////////////
*/
#endregion user code

        int state;
        int currentStart = startState[0];
        int chr;           // last character read
        int cNum = 0;      // ordinal number of chr
        int lNum = 0;      // current line number
        int lineStartNum;  // ordinal number at start of line
        //
        // The following instance variables are used, among other
        // things, for constructing the yylloc location objects.
        //
        int tokPos;        // buffer position at start of token
        int tokNum;        // ordinal number of first character
        int tokLen;        // number of characters in token
        int tokCol;        // zero-based column number at start of token
        int tokLin;        // line number at start of token
        int tokEPos;       // buffer position at end of token
        int tokECol;       // column number at end of token
        int tokELin;       // line number at end of token
        string tokTxt;     // lazily constructed text of token
#if STACK          
        private Stack<int> scStack = new Stack<int>();
#endif // STACK

#region ScannerTables
    struct Table {
        public int min; public int rng; public int dflt;
        public sbyte[] nxt;
        public Table(int m, int x, int d, sbyte[] n) {
            min = m; rng = x; dflt = d; nxt = n;
        }
    };

    static int[] startState = {111, 0};

#region CompressedCharacterMap
    //
    // There are 56 equivalence classes
    // There are 4 character sequence regions
    // There are 1 tables, 127 entries
    // There are 3 runs, 0 singletons
    // Decision tree depth is 2
    //
    static sbyte[] mapC0 = new sbyte[127] {
/*     '\0' */ 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 0, 3, 3, 4, 3, 3, 
/*   '\x10' */ 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
/*   '\x20' */ 4, 43, 23, 3, 33, 48, 36, 3, 46, 52, 2, 32, 42, 38, 30, 1, 
/*      '0' */ 24, 25, 25, 25, 25, 25, 25, 25, 29, 29, 41, 53, 47, 37, 39, 49, 
/*      '@' */ 3, 35, 35, 35, 35, 31, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
/*      'P' */ 35, 35, 35, 35, 35, 35, 35, 35, 28, 35, 35, 45, 27, 51, 40, 35, 
/*      '`' */ 27, 20, 19, 14, 7, 9, 6, 34, 18, 5, 34, 21, 10, 34, 13, 8, 
/*      'p' */ 34, 34, 16, 11, 15, 12, 22, 17, 26, 34, 34, 44, 55, 50, 54 };

    sbyte MapC(int chr)
    { // '\0' <= chr <= '\U0010FFFF'
      if (chr < 1040) // '\0' <= chr <= '\u040F'
        if (chr < 127) // '\0' <= chr <= '~'
          return mapC0[chr - 0];
        else // '\x7F' <= chr <= '\u040F'
          return (sbyte)3;
      else // '\u0410' <= chr <= '\U0010FFFF'
        if (chr < 1104) // '\u0410' <= chr <= '\u044F'
          return (sbyte)34;
        else // '\u0450' <= chr <= '\U0010FFFF'
          return (sbyte)3;
    }
#endregion

    static Table[] NxS = new Table[117];

    static Scanner() {
    NxS[0] = new Table(0, 0, 0, null);
    NxS[1] = new Table(0, 5, -1, new sbyte[] {1, -1, -1, -1, 1});
    NxS[2] = new Table(37, 22, -1, new sbyte[] {109, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 108, 115});
    NxS[3] = new Table(37, 1, -1, new sbyte[] {107});
    NxS[4] = new Table(0, 0, -1, null);
    NxS[5] = new Table(5, 31, -1, new sbyte[] {8, 106, 8, 8, 8, 8, 
          8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[6] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 8, 8, 
          8, 99, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[7] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 98, 8, 8, 
          8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[8] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 8, 8, 
          8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[9] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 8, 95, 
          8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[10] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 88, 8, 8, 
          8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[11] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 83, 8, 
          8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[12] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 8, 8, 
          8, 8, 8, 8, 8, 8, 8, 79, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[13] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 8, 8, 
          8, 8, 8, 8, 8, 75, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[14] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 8, 8, 
          8, 8, 8, 8, 8, 8, 8, 8, 8, 73, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[15] = new Table(0, 24, 15, new sbyte[] {-1, 15, 15, 15, 15, 15, 
          15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 
          15, 72});
    NxS[16] = new Table(9, 23, -1, new sbyte[] {68, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, 70, 70, 114, -1, 114, 17, 113, 
          68});
    NxS[17] = new Table(9, 23, -1, new sbyte[] {68, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, 17, 17, -1, -1, -1, 17, 113, 
          68});
    NxS[18] = new Table(2, 29, -1, new sbyte[] {65, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          66, 66, -1, -1, -1, 66, 112});
    NxS[19] = new Table(32, 6, -1, new sbyte[] {63, -1, -1, -1, -1, 64});
    NxS[20] = new Table(33, 24, 61, new sbyte[] {-1, 61, 61, 61, 61, 61, 
          61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 
          61, 60});
    NxS[21] = new Table(36, 2, -1, new sbyte[] {58, 59});
    NxS[22] = new Table(37, 1, -1, new sbyte[] {57});
    NxS[23] = new Table(37, 3, -1, new sbyte[] {53, 54, 55});
    NxS[24] = new Table(37, 3, -1, new sbyte[] {50, -1, 51});
    NxS[25] = new Table(37, 1, -1, new sbyte[] {49});
    NxS[26] = new Table(41, 1, -1, new sbyte[] {48});
    NxS[27] = new Table(0, 0, -1, null);
    NxS[28] = new Table(37, 1, -1, new sbyte[] {47});
    NxS[29] = new Table(0, 0, -1, null);
    NxS[30] = new Table(0, 0, -1, null);
    NxS[31] = new Table(0, 0, -1, null);
    NxS[32] = new Table(37, 11, -1, new sbyte[] {44, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, 45});
    NxS[33] = new Table(37, 1, -1, new sbyte[] {43});
    NxS[34] = new Table(0, 0, -1, null);
    NxS[35] = new Table(0, 0, -1, null);
    NxS[36] = new Table(0, 0, -1, null);
    NxS[37] = new Table(0, 0, -1, null);
    NxS[38] = new Table(0, 0, -1, null);
    NxS[39] = new Table(0, 0, -1, null);
    NxS[40] = new Table(37, 19, -1, new sbyte[] {41, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 42});
    NxS[41] = new Table(0, 0, -1, null);
    NxS[42] = new Table(0, 0, -1, null);
    NxS[43] = new Table(0, 0, -1, null);
    NxS[44] = new Table(0, 0, -1, null);
    NxS[45] = new Table(37, 1, -1, new sbyte[] {46});
    NxS[46] = new Table(0, 0, -1, null);
    NxS[47] = new Table(0, 0, -1, null);
    NxS[48] = new Table(0, 0, -1, null);
    NxS[49] = new Table(0, 0, -1, null);
    NxS[50] = new Table(0, 0, -1, null);
    NxS[51] = new Table(37, 1, -1, new sbyte[] {52});
    NxS[52] = new Table(0, 0, -1, null);
    NxS[53] = new Table(0, 0, -1, null);
    NxS[54] = new Table(0, 0, -1, null);
    NxS[55] = new Table(2, 1, -1, new sbyte[] {56});
    NxS[56] = new Table(0, 0, -1, null);
    NxS[57] = new Table(0, 0, -1, null);
    NxS[58] = new Table(0, 0, -1, null);
    NxS[59] = new Table(0, 0, -1, null);
    NxS[60] = new Table(33, 1, 60, new sbyte[] {-1});
    NxS[61] = new Table(33, 24, 61, new sbyte[] {62, 61, 61, 61, 61, 61, 
          61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 
          61, 60});
    NxS[62] = new Table(0, 0, -1, null);
    NxS[63] = new Table(0, 0, -1, null);
    NxS[64] = new Table(0, 0, -1, null);
    NxS[65] = new Table(0, 0, -1, null);
    NxS[66] = new Table(9, 23, -1, new sbyte[] {68, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, 66, 66, -1, -1, -1, 66, -1, 
          68});
    NxS[67] = new Table(0, 0, -1, null);
    NxS[68] = new Table(24, 15, -1, new sbyte[] {69, 69, -1, -1, -1, 69, 
          -1, -1, 69, -1, -1, -1, -1, -1, 69});
    NxS[69] = new Table(24, 6, -1, new sbyte[] {69, 69, -1, -1, -1, 69});
    NxS[70] = new Table(9, 23, -1, new sbyte[] {68, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, 70, 70, -1, -1, -1, 17, 113, 
          68});
    NxS[71] = new Table(6, 46, -1, new sbyte[] {71, 71, -1, 71, -1, -1, 
          -1, -1, 71, -1, -1, -1, -1, 71, 71, -1, -1, -1, 71, 71, -1, 71, 
          71, 71, -1, 71, -1, -1, -1, 71, -1, -1, -1, -1, 71, -1, -1, -1, 
          -1, 71, -1, -1, -1, -1, -1, 71});
    NxS[72] = new Table(0, 0, -1, null);
    NxS[73] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 8, 8, 
          8, 8, 8, 8, 8, 74, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[74] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 8, 8, 
          8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[75] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 76, 8, 
          8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[76] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 8, 8, 
          8, 8, 8, 8, 8, 8, 8, 8, 8, 77, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[77] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 8, 8, 
          8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 78, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[78] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 8, 8, 
          8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[79] = new Table(5, 31, -1, new sbyte[] {80, 8, 8, 8, 8, 8, 
          8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[80] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 8, 81, 
          8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[81] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 82, 8, 
          8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[82] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 8, 8, 
          8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[83] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 8, 8, 
          8, 8, 8, 8, 84, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[84] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 8, 8, 
          8, 85, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[85] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 8, 8, 
          8, 8, 8, 8, 8, 86, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[86] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 8, 8, 
          8, 8, 87, 8, 8, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[87] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 8, 8, 
          8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[88] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 8, 8, 
          8, 8, 89, 8, 8, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[89] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 8, 8, 
          8, 8, 8, 8, 90, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[90] = new Table(5, 31, -1, new sbyte[] {91, 8, 8, 8, 8, 8, 
          8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[91] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 8, 8, 
          8, 8, 92, 8, 8, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[92] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 8, 8, 
          8, 93, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[93] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 94, 8, 
          8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[94] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 8, 8, 
          8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[95] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 8, 8, 
          96, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[96] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 97, 8, 
          8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[97] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 8, 8, 
          8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[98] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 8, 8, 
          8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[99] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 8, 8, 
          8, 8, 100, 8, 8, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[100] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 8, 8, 
          8, 8, 8, 101, 8, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[101] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 8, 8, 
          8, 8, 8, 8, 102, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[102] = new Table(5, 31, -1, new sbyte[] {103, 8, 8, 8, 8, 8, 
          8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[103] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 104, 8, 8, 
          8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[104] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 8, 8, 
          8, 8, 105, 8, 8, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[105] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 8, 8, 
          8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[106] = new Table(5, 31, -1, new sbyte[] {8, 8, 8, 8, 8, 8, 
          8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, -1, 8, 8, 8, 
          -1, 8, 8, -1, 8, -1, -1, 8, 8});
    NxS[107] = new Table(0, 0, -1, null);
    NxS[108] = new Table(0, 1, 108, new sbyte[] {-1});
    NxS[109] = new Table(0, 0, -1, null);
    NxS[110] = new Table(2, 1, 115, new sbyte[] {116});
    NxS[111] = new Table(14, 52, 8, new sbyte[] {10, 8, 11, 12, 8, 13, 
          8, 8, 14, 15, 16, 17, 8, 4, 8, 17, 18, 8, 19, 20, 8, 8, 
          21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 
          37, 38, 39, 40, 1, 2, 3, 4, 1, 5, 6, 7, 8, 9});
    NxS[112] = new Table(30, 1, -1, new sbyte[] {67});
    NxS[113] = new Table(24, 6, -1, new sbyte[] {66, 66, -1, -1, -1, 66});
    NxS[114] = new Table(6, 46, -1, new sbyte[] {71, 71, -1, 71, -1, -1, 
          -1, -1, 71, -1, -1, -1, -1, 71, 71, -1, -1, -1, 71, 71, -1, 71, 
          71, 71, -1, 71, -1, -1, -1, 71, -1, -1, -1, -1, 71, -1, -1, -1, 
          -1, 71, -1, -1, -1, -1, -1, 71});
    NxS[115] = new Table(2, 1, 115, new sbyte[] {116});
    NxS[116] = new Table(1, 2, 115, new sbyte[] {110, 116});
    }

int NextState(int qStat) {
    if (chr == ScanBuff.EOF)
        return eofNum;
    else {
        int rslt;
        int idx = MapC(chr) - NxS[qStat].min;
        if (idx < 0) idx += 56;
        if ((uint)idx >= (uint)NxS[qStat].rng) rslt = NxS[qStat].dflt;
        else rslt = NxS[qStat].nxt[idx];
        return rslt;
    }
}

int NextState() {
    if (chr == ScanBuff.EOF)
        return eofNum;
    else {
        int rslt;
        int idx = MapC(chr) - NxS[state].min;
        if (idx < 0) idx += 56;
        if ((uint)idx >= (uint)NxS[state].rng) rslt = NxS[state].dflt;
        else rslt = NxS[state].nxt[idx];
        return rslt;
    }
}

// EXPERIMENTAL: This is the NextState method that
// is used by the CharClassPredicate functions for V0.9
int TestNextState(int qStat, int chr) {
    if (chr == ScanBuff.EOF)
        return eofNum;
    else {
        int rslt;
        int idx = MapC(chr) - NxS[qStat].min;
        if (idx < 0) idx += 56;
        if ((uint)idx >= (uint)NxS[qStat].rng) rslt = NxS[qStat].dflt;
        else rslt = NxS[qStat].nxt[idx];
        return rslt;
    }
}

#endregion


#if BACKUP
        // ==============================================================
        // == Nested class used for backup in automata which do backup ==
        // ==============================================================

        internal class Context // class used for automaton backup.
        {
            public int bPos;
            public int cNum;
            public int lNum; // Need this in case of backup over EOL.
            public int state;
            public int cChr;
        }
#endif // BACKUP

        // ==============================================================
        // ==== Nested struct to support input switching in scanners ====
        // ==============================================================

		struct BufferContext {
			internal ScanBuff buffSv;
			internal int chrSv;
			internal int cNumSv;
			internal int lNumSv;
			internal int startSv;
		}
		
#region Buffer classes

        // ==============================================================
        // ===== Private methods to save and restore buffer contexts ====
        // ==============================================================

        /// <summary>
        /// This method creates a buffer context record from
        /// the current buffer object, together with some
        /// scanner state values. 
        /// </summary>
		BufferContext MkBuffCtx()
		{
			BufferContext rslt;
			rslt.buffSv = this.buffer;
			rslt.chrSv = this.chr;
			rslt.cNumSv = this.cNum;
			rslt.lNumSv = this.lNum;
			rslt.startSv = this.lineStartNum;
			return rslt;
		}

        /// <summary>
        /// This method restores the buffer value and allied
        /// scanner state from the given context record value.
        /// </summary>
		void RestoreBuffCtx(BufferContext value)
		{
			this.buffer = value.buffSv;
			this.chr = value.chrSv;
			this.cNum = value.cNumSv;
			this.lNum = value.lNumSv;
			this.lineStartNum = value.startSv;
        } 
        
        // ==============================================================
        // ===== Nested classes for various ScanBuff derived classes ====
        // ==============================================================
        // =============== Nested class for string input ================
        // ==============================================================

        /// <summary>
        /// This class read characters from a single string as
        /// required, for example, by Visual Studio language services
        /// </summary>
        public sealed class StringBuff : ScanBuff
        {
            string str;        // input buffer
            int bPos;          // current position in buffer
            int sLen;

            public StringBuff(string str)
            {
                this.str = str;
                this.sLen = str.Length;
            }

            private int Read16()
            {
                if (bPos < sLen) return str[bPos++];
#if BABEL
                else if (bPos == sLen) { bPos++; return '\n'; }   // one strike, see newline
#endif // BABEL
                else { bPos++; return EOF; }                      // two strikes and you're out!
            }
            
            /// <summary>
            /// Read returns UTF32 in this application.
            /// </summary>
            /// <returns>Unicode point as an int [0 .. 0xFFFFF]; -1 for EOF</returns>
            public override int Read()
            {
                int utf16 = Read16();
                if (utf16 < 0xD800 || utf16 > 0xDBFF)
                    return utf16;
                else
                {
                    int low16 = Read16();
                    if (low16 < 0xDC00 || low16 > 0xDFFF)
                        return UnicodeReplacementChar;
                    else
                        return (0x10000 + (utf16 & 0x3FF << 10) + (low16 & 0x3FF));
                }
            }
            
            public override int ReadPos { get { return bPos - 1; } }

            public override int Peek()
            {
                if (bPos < sLen) return str[bPos];
                else return '\n';
            }

            public override string GetString(int beg, int end)
            {
                //  "end" can be greater than sLen with the BABEL
                //  option set.  Read returns a "virtual" EOL if
                //  an attempt is made to read past the end of the
                //  string buffer.  Without the guard any attempt 
                //  to fetch yytext for a token that includes the 
                //  EOL will throw an index exception.
                if (end > sLen) end = sLen;
                if (end <= beg) return ""; 
                else return str.Substring(beg, end - beg);
            }

            public override int Pos
            {
                get { return bPos; }
                set { bPos = value; }
            }
        }

#if !NOFILES
       // ====================== Nested class ==========================
       //  The LineBuff class contributed by Nigel Horspool, 
       //  nigelh@cs.uvic.cs
       // ==============================================================

        public sealed class LineBuff : ScanBuff
        {
            IList<string> line;    // list of source lines from a file
            int numLines;          // number of strings in line list
            string curLine;        // current line in that list
            int cLine;             // index of current line in the list
            int curLen;            // length of current line
            int curLineStart;      // position of line start in whole file
            int curLineEnd;        // position of line end in whole file
            int maxPos;            // max position ever visited in whole file
            int cPos;              // ordinal number of chr in source

            // Constructed from a list of strings, one per source line.
            // The lines have had trailing '\n' characters removed.
            public LineBuff(IList<string> lineList)
            {
                line = lineList;
                numLines = line.Count;
                cPos = curLineStart = 0;
                curLine = (numLines>0 ? line[0] : "");
                maxPos = curLineEnd = curLen = curLine.Length;
                cLine = 1;
            }

            public override int Read()
            {
                if (cPos < curLineEnd)
                    return curLine[cPos++ - curLineStart];
                if (cPos++ == curLineEnd)
                    return '\n';
                if (cLine >= numLines)
                    return EOF;
                curLine = line[cLine];
                curLen = curLine.Length;
                curLineStart = curLineEnd + 1;
                curLineEnd = curLineStart + curLen;
                if (curLineEnd>maxPos)
                    maxPos = curLineEnd;
                cLine++;
                return curLen>0? curLine[0] : '\n';
            }

            public override int Peek()
            {
                return (cPos < curLineEnd)? curLine[cPos - curLineStart] : '\n';
            }

            // To speed up searches for the line containing a position
            private int cachedPos = 0;
            private int cachedIx = 0;
            private int cachedLstart = 0;

            // Given a position pos within the entire source, the results are
            //   ix     -- the index of the containing line
            //   lstart -- the position of the first character on that line
            private void findIndex( int pos, out int ix, out int lstart )
            {
                if (pos >= cachedPos) {
                    ix = cachedIx;  lstart = cachedLstart;
                } else {
                    ix = lstart = 0;
                }
                for( ; ; ) {
                    int len = line[ix].Length + 1;
                    if (pos < lstart+len) break;
                    lstart += len;
                    ix++;
                }
                cachedPos = pos;
                cachedIx = ix;
                cachedLstart = lstart;
            }
        
            public override string GetString(int beg, int end)
            {
                if (beg >= maxPos || end <= beg) return "";
                int endIx, begIx, endLineStart, begLineStart;
                findIndex(beg, out begIx, out begLineStart);
                int begCol = beg - begLineStart;
                findIndex(end, out endIx, out endLineStart);
                int endCol = end - endLineStart;
                string s = line[begIx];
                if (begIx == endIx) {
                    // the usual case, substring all on one line
                    return (endCol <= s.Length)?
                        s.Substring(begCol, endCol-begCol)
                        : s.Substring(begCol) + "\n";
                }
                // the string spans multiple lines, yuk!
                StringBuilder sb = new StringBuilder();
                if (begCol < s.Length)
                    sb.Append(s.Substring(begCol));
                for( ; ; ) {
                    sb.Append("\n");
                    s = line[++begIx];
                    if (begIx >= endIx) break;
                    sb.Append(s);
                }
                if (endCol <= s.Length) {
                    sb.Append(s.Substring(0, endCol));
                } else {
                    sb.Append(s);
                    sb.Append("\n");
                }
                return sb.ToString();
            }

            public override int Pos
            {
                get { return cPos; }
                set {
                    cPos = value;
                    findIndex(cPos, out cLine, out curLineStart);
                    curLine = line[cLine];
                    curLineEnd = curLineStart+curLine.Length;
                }
            }
            
            public override int ReadPos { get { return cPos - 1; } }
        }
        
        // ==============================================================
        // =========== Nested class StreamBuff : byte files =============
        // ==============================================================

        /// <summary>
        /// This is the Buffer for byte files. It returns 8-bit characters.
        /// </summary>
        public class StreamBuff : ScanBuff
        {
            protected BufferedStream bStrm;   // input buffer
            protected int delta = 1;          // number of bytes in chr, could be 0 for EOF.

            public StreamBuff(Stream str) { this.bStrm = new BufferedStream(str); }

            /// <summary>
            /// Read returns subset [0 .. 0xFF] in this application.
            /// </summary>
            /// <returns>Unicode point as an int [0 .. 0xFF]; -1 for EOF</returns>
            public override int Read() {
                int ch0 = bStrm.ReadByte();
                delta = (ch0 == EOF ? 0 : 1);
                return ch0; 
            }
            
            public override int ReadPos {
                get { return (int)bStrm.Position - delta; }
            }

            public override int Peek()
            {
                int rslt = bStrm.ReadByte();
                bStrm.Seek(-delta, SeekOrigin.Current);
                return rslt;
            }

            public override string GetString(int beg, int end)
            {
                if (end - beg <= 0) return "";
                long savePos = bStrm.Position;
                char[] arr = new char[end - beg];
                bStrm.Position = (long)beg;
                for (int i = 0; i < (end - beg); i++)
                    arr[i] = (char)bStrm.ReadByte();
                bStrm.Position = savePos;
                return new String(arr);
            }

            // Pos is the position *after* reading chr!
            public override int Pos
            {
                get { return (int)bStrm.Position; }
                set { bStrm.Position = value; }
            }
            
            public static int GetCodePage(string command)
            {
                command = command.ToLower();
                if (command.StartsWith("codepage:"))
                    command = command.Substring(9);
                try
                {
                    if (command.Equals("raw"))
                        return -1;
                    else if (command.Equals("guess"))
                        return -2;
                    else if (command.Equals("default"))
                        return 0;
                    else if (char.IsDigit(command[0]))
                        return int.Parse(command);
                    else
                    {
                        Encoding enc = Encoding.GetEncoding(command);
                        return enc.CodePage;
                    }
                }
                catch
                {
                    Console.Error.WriteLine(
                        "Unknown codepage \"{0}\", using machine default", command);
                    return 0;
                }
            }
        }

#if !BYTEMODE       
        // ==============================================================
        // ===== Nested class CodePageBuff : for unicode text files =====
        // ========= Byte files mapped by a specified CodePage ==========
        // ==============================================================

        public sealed class CodePageBuff : StreamBuff
        {
        
            char[] map = new char[256];
            
            public CodePageBuff(Stream stream) : this(stream, Encoding.Default) { }

            
            public CodePageBuff(Stream stream, Encoding enc) : base(stream)
            {
                bool done;
                int bNum, cNum;
                byte[] bArray = new byte[256];
                if (!enc.IsSingleByte)
                    throw new NotImplementedException(
                        "Only UTF-8, UTF-16 and single-byte code pages allowed");
                Decoder decoder = enc.GetDecoder();
                for (int i = 0; i < 256; i++)
                    bArray[i] = (byte)i;
                decoder.Convert(bArray, 0, 256, this.map, 0, 256, true, out bNum, out cNum, out done);
            }
            
            /// <summary>
            /// Read returns subset unicode char corresponding to the
            /// given character in the chosen codepage.
            /// </summary>
            /// <returns>Unicode point as an int; -1 for EOF</returns>
            public override int Read() {
                int ch0 = bStrm.ReadByte();
                if (ch0 == EOF)
                {
                    delta = 0; return -1;
                }
                else
                {
                    delta = 1; return this.map[ch0];
                } 
            }
            
            public override string GetString(int beg, int end)
            {
                if (end - beg <= 0) return "";
                long savePos = bStrm.Position;
                int saveDelta = delta;
                char[] arr = new char[end - beg];
                bStrm.Position = (long)beg;
                for (int i = 0; i < (end - beg); i++)
                    arr[i] = (char)Read();
                bStrm.Position = savePos;
                delta = saveDelta;
                return new String(arr);
            }
        }
        

        // ==============================================================
        // ====== Nested class TextBuff : for unicode text files ========
        // ==== This is the UTF8 class, UTF16 handled by subclasses =====
        // ==============================================================

        /// <summary>
        /// This is the Buffer for UTF8 files.
        /// It attempts to read the encoding preamble, which for 
        /// this encoding should be unicode point \uFEFF which is 
        /// encoded as EF BB BF
        /// </summary>
        public class TextBuff : ScanBuff
        {
            protected BufferedStream bStrm;   // input buffer
            protected int delta = 1;          // length of chr, zero for EOF!
            

            /// <summary>
            /// TextBuff factory.  Reads the file preamble
            /// and returns a TextBuff, LittleEndTextBuff or
            /// BigEndTextBuff according to the result.
            /// </summary>
            /// <param name="strm">The underlying stream</param>
            /// <returns></returns>
            public static ScanBuff NewTextBuff(Stream strm, int fallbackCodepage)
            {
                // First check if this is a UTF16 file
                //
                int b0 = strm.ReadByte();
                int b1 = strm.ReadByte();

                if (b0 == 0xfe && b1 == 0xff)
                    return new BigEndTextBuff(strm);
                if (b0 == 0xff && b1 == 0xfe)
                    return new LittleEndTextBuff(strm);
                
                int b2 = strm.ReadByte();
                if (b0 == 0xef && b1 == 0xbb && b2 == 0xbf)
                    return new TextBuff(strm);
                //
                // There is no unicode preamble, so
                // we go back to the bytefile default.
                //
                strm.Seek(0, SeekOrigin.Begin);
                
                switch (fallbackCodepage)
                {
                    case -2:
                        {
                            int guess = new Guesser.Scanner(strm).GuessCodepage();
                            strm.Seek(0, SeekOrigin.Begin);
                            if (guess == 0)
                                return new CodePageBuff(strm);
                            else if (guess == 65001)
                                return new TextBuff(strm);
                            else
                                return new StreamBuff(strm);
                        }                        
                    case -1:
                        return new StreamBuff(strm);
                    case 0:
                        return new CodePageBuff(strm); // Default codepage
                    case 65001:
                        return new TextBuff(strm);
                    case 1200:
                        return new LittleEndTextBuff(strm);
                    case 1201:
                        return new BigEndTextBuff(strm);
                    default:
                        return new CodePageBuff(strm, Encoding.GetEncoding(fallbackCodepage));
                }
            }

            protected TextBuff(Stream str) { 
                this.bStrm = new BufferedStream(str);
            }

            /// <summary>
            /// Read returns UTF32 in this application.
            /// </summary>
            /// <returns>Unicode point as an int [0 .. 0xFFFFF]; -1 for EOF</returns>
            public override int Read()
            {
                int ch0 = bStrm.ReadByte();
                int ch1, ch2, ch3,ch4, ch5;
                int result = UnicodeReplacementChar;

                if (ch0 < 0x7f)
                {
                    delta = (ch0 == EOF ? 0 : 1);
                    result = ch0;
                }
                else if ((ch0 & 0xe0) == 0xc0)
                {
                    delta = 2;
                    ch1 = bStrm.ReadByte();
                    if ((ch1 & 0xc0) == 0x80)
                        result = ((ch0 & 0x1f) << 6) + (ch1 & 0x3f);
                }
                else if ((ch0 & 0xf0) == 0xe0)
                {
                    delta = 3;
                    ch1 = bStrm.ReadByte(); ch2 = bStrm.ReadByte();
                    if ((ch1 & 0xc0) == 0x80 && (ch2 & 0xc0) == 0x80)
                        result = ((ch0 & 0xf) << 12) + ((ch1 & 0x3f) << 6) + (ch2 & 0x3f);
                }
                else if ((ch0 & 0xf8) == 0xf0)
                {
                    delta = 4;
                    ch1 = bStrm.ReadByte(); ch2 = bStrm.ReadByte(); ch3 = bStrm.ReadByte();
                    if ((ch1 & 0xc0) == 0x80 && (ch2 & 0xc0) == 0x80 && (ch3 & 0xc0) == 0x80)
                    {
                        result = ((ch0 & 0x7) << 18) + ((ch1 & 0x3f) << 12) + 
                                 ((ch2 & 0x3f) << 6) + (ch3 & 0x3f);
                    }
                }
                else if ((ch0 & 0xfc) == 0xf8)
                {
                    delta = 5;
                    ch1 = bStrm.ReadByte(); ch2 = bStrm.ReadByte();
                    ch3 = bStrm.ReadByte(); ch4 = bStrm.ReadByte();
                    if ((ch1 & 0xc0) == 0x80 && (ch2 & 0xc0) == 0x80 && (ch3 & 0xc0) == 0x80 && (ch4 & 0xc0) == 0x80)
                    {
                        result = ((ch0 & 0x3) << 24) + ((ch1 & 0x3f) << 18) + 
                                     ((ch2 & 0x3f) << 12) + ((ch3 & 0x3f) << 6) + (ch4 & 0x3f);
                    }
                }
                else if ((ch0 & 0xfe) == 0xfc)
                {
                    delta = 6;
                    ch1 = bStrm.ReadByte(); ch2 = bStrm.ReadByte(); ch3 = bStrm.ReadByte();
                    ch4 = bStrm.ReadByte(); ch5 = bStrm.ReadByte();

                    if ((ch1 & 0xc0) == 0x80 && (ch2 & 0xc0) == 0x80 && 
                        (ch3 & 0xc0) == 0x80 && (ch4 & 0xc0) == 0x80 && (ch5 & 0xc0) == 0x80)
                    {
                        result = ((ch0 & 0x1) << 28) + ((ch1 & 0x3f) << 24) + ((ch2 & 0x3f) << 18) + 
                                     ((ch3 & 0x3f) << 12) + ((ch4 & 0x3f) << 6) + (ch5 & 0x3f);
                    }
                }
                return result;
            }

            public sealed override int ReadPos
            {
                get { return (int)bStrm.Position - delta; }
            }

            public sealed override int Peek()
            {
                int rslt = Read();
                bStrm.Seek(-delta, SeekOrigin.Current);
                return rslt;
            }

            /// <summary>
            /// Returns the string from the buffer between
            /// the given file positions.  This needs to be
            /// done carefully, as the number of characters
            /// is, in general, not equal to (end - beg).
            /// </summary>
            /// <param name="beg">Begin filepos</param>
            /// <param name="end">End filepos</param>
            /// <returns></returns>
            public override string GetString(int beg, int end)
            {
                int i;
                if (end - beg <= 0) return "";
                long savePos = bStrm.Position;
                int saveDelta = delta;
                //
                //  The length of the array cannot be larger than
                //  end - beg, since if the characters expand by 
                //  using surrogate pairs the UTF8 must have taken
                //  up at least four bytes for any such character.
                //
                char[] arr = new char[end - beg];
                
                bStrm.Position = (long)beg;
                // Normally each call of Read() returns a valid UTF16
                // value which will take up one place in the string.
                // However, if read returns a value > 0xFFFF then a
                // *pair* of surrogate characters must be added.
                for (i = 0; bStrm.Position < end; i++)
                {
                    int value = Read();
                    if (value < 0xFFFF)
                        arr[i] = (char)value;
                    else
                    {
                        int temp = value - 0x10000;
                        arr[i++] = (char)(0xD800 + temp / 1024);
                        arr[i]   = (char)(0xDC00 + temp % 1024);
                    }
                }
                bStrm.Position = savePos;
                delta = saveDelta;
                return new String(arr, 0, i);
            }

            // Pos is the position *after* reading chr!
            public sealed override int Pos
            {
                get { return (int)bStrm.Position; }
                set { bStrm.Position = value; }
            }
        }
        
        // ==============================================================
        // ====================== Nested class ==========================
        // ==============================================================
        
        /// <summary>
        /// This is the Buffer for Big-endian UTF16 files.
        /// </summary>
        public sealed class BigEndTextBuff : TextBuff
        {
            internal BigEndTextBuff(Stream str) : base(str) { } // 

            private int Read16()
            {
                int ch0 = bStrm.ReadByte();
                int ch1 = bStrm.ReadByte();
                if (ch1 == EOF)
                {
                    // An EOF in either byte counts as an EOF
                    delta = (ch0 == EOF ? 0 : 1);
                    return -1;
                }
                else
                {
                    delta = 2;
                    return (ch0 << 8) + ch1;
                }
            }
            
            /// <summary>
            /// Read returns UTF32 in this application.
            /// </summary>
            /// <returns>Unicode point as an int [0 .. 0xFFFFF]; -1 for EOF</returns>
            public override int Read()
            {
                int utf16 = Read16();
                if (utf16 < 0xD800 || utf16 > 0xDBFF)
                    return utf16;
                else
                {
                    int low16 = Read16();
                    delta = 4;
                    if (low16 < 0xDC00 || low16 > 0xDFFF)
                        return UnicodeReplacementChar;
                    else
                        return (0x10000 + (utf16 & 0x3FF << 10) + (low16 & 0x3FF));
                }
            }
            
            /// <summary>
            /// Returns the string from the buffer between
            /// the given file positions.  This needs to be
            /// done carefully, as the number of characters
            /// is, in general, not equal to (end - beg).
            /// </summary>
            /// <param name="beg">Begin filepos</param>
            /// <param name="end">End filepos</param>
            /// <returns></returns>
            public sealed override string GetString(int beg, int end)
            {
                int i;
                if (end - beg <= 0) return "";
                long savePos = bStrm.Position;
                int saveDelta = delta;
                char[] arr = new char[end - beg];
                bStrm.Position = (long)beg;
                // This stream will have utf16 valid for strings
                for (i = 0; bStrm.Position < end; i++)
                    arr[i] = (char)Read();
                bStrm.Position = savePos;
                delta = saveDelta;
                return new String(arr, 0, i);
            }
        }

        // ==============================================================
        // ====================== Nested class ==========================
        // ==============================================================
        
        /// <summary>
        /// This is the Buffer for Little-endian UTF16 files.
        /// </summary>
        public sealed class LittleEndTextBuff : TextBuff
        {
            internal LittleEndTextBuff(Stream str) : base(str) { } // { this.bStrm = new BufferedStream(str); }

            private int Read16()
            {
                int ch0 = bStrm.ReadByte();
                int ch1 = bStrm.ReadByte();
                if (ch1 == EOF)
                {
                    // An EOF in either byte counts as an EOF
                    delta = (ch0 == EOF ? 0 : 1);
                    return -1;
                }
                else
                {
                    delta = 2;
                    return (ch1 << 8) + ch0;
                }
            }
            
            /// <summary>
            /// Read returns UTF32 in this application.
            /// </summary>
            /// <returns>Unicode point as an int [0 .. 0xFFFFF]; -1 for EOF</returns>
            public override int Read()
            {
                int utf16 = Read16();
                if (utf16 < 0xD800 || utf16 > 0xDBFF)
                    return utf16;
                else
                {
                    int low16 = Read16();
                    delta = 4;
                    if (low16 < 0xDC00 || low16 > 0xDFFF)
                        return UnicodeReplacementChar;
                    else
                        return (0x10000 + (utf16 & 0x3FF << 10) + (low16 & 0x3FF));
                }
            }
            
            /// <summary>
            /// Returns the string from the buffer between
            /// the given file positions.  This needs to be
            /// done carefully, as the number of characters
            /// is, in general, not equal to (end - beg).
            /// </summary>
            /// <param name="beg">Begin filepos</param>
            /// <param name="end">End filepos</param>
            /// <returns></returns>
            public sealed override string GetString(int beg, int end)
            {
                int i;
                if (end - beg <= 0) return "";
                long savePos = bStrm.Position;
                int saveDelta = delta;
                char[] arr = new char[end - beg];
                bStrm.Position = (long)beg;
                // This stream will have utf16 valid for strings
                for (i = 0; bStrm.Position < end; i++)
                    arr[i] = (char)Read16();
                bStrm.Position = savePos;
                delta = saveDelta;
                return new String(arr, 0, i);
            }
        }
#endif // !BYTEMODE
#endif // !NOFILES
#endregion Buffer classes

        // =================== End Nested classes =======================

#if !NOFILES
        public Scanner(Stream file) {
            SetSource(file, 65001); // unicode option
        }

        public Scanner(Stream file, string codepage) {
            SetSource(file, Scanner.StreamBuff.GetCodePage(codepage));
        }
        
#endif // !NOFILES

        public Scanner() { }

        void GetChr()
        {
            if (chr == '\n')  // This needs to be fixed for other conventions
            { 
                lineStartNum = cNum + 1; 
                lNum++; 
            }
            chr = buffer.Read();
            cNum++;
        }

        void MarkToken()
        {
            tokPos = buffer.ReadPos;
            tokNum = cNum;
            tokLin = lNum;
            tokCol = cNum - lineStartNum;
        }
        
        void MarkEnd()
        {
            tokTxt = null;
            tokLen = cNum - tokNum;
            tokEPos = buffer.ReadPos;
            tokELin = lNum;
            tokECol = cNum - lineStartNum;
        }

        // ==============================================================
        // =====    Initialization of string-based input buffers     ====
        // ==============================================================

        /// <summary>
        /// Create and initialize a StringBuff buffer object for this scanner
        /// </summary>
        /// <param name="source">the input string</param>
        /// <param name="offset">starting offset in the string</param>
        public void SetSource(string source, int offset)
        {
            this.buffer = new StringBuff(source);
            this.buffer.Pos = offset;
            this.lNum = 0;
            this.cNum = offset - 1;
            this.chr = '\n'; // to initialize yyline, yycol and lineStart
            GetChr();
        }

#if !NOFILES        
        // ================ LineBuffer Initialization ===================

        /// <summary>
        /// Create and initialize a LineBuff buffer object for this scanner
        /// </summary>
        /// <param name="source">the list of input strings</param>
        public void SetSource(IList<string> source)
        {
            this.buffer = new LineBuff(source);
            this.chr = '\n'; // to initialize yyline, yycol and lineStart
            this.lNum = 0;
            this.cNum = -1;
            GetChr();
        }

        // =============== StreamBuffer Initialization ==================

        /// <summary>
        /// Create and initialize a StreamBuff buffer object for this scanner.
        /// StreamBuff is buffer for 8-bit byte files.
        /// </summary>
        /// <param name="source">the input byte stream</param>
        public void SetSource(Stream source)
        {
            this.buffer = new StreamBuff(source);
            this.lNum = 0;
            this.cNum = -1;
            this.chr = '\n'; // to initialize yyline, yycol and lineStart
            GetChr();
        }
        
#if !BYTEMODE
        // ================ TextBuffer Initialization ===================

        /// <summary>
        /// Create and initialize a TextBuff buffer object for this scanner.
        /// TextBuff is a buffer for encoded unicode files.
        /// </summary>
        /// <param name="source">the input text file</param>
        /// <param name="fallbackCodepage">Codepage to use if file has
        /// no BOM. For 0, use machine default; for -1, 8-bit binary</param>
        public void SetSource(Stream source, int fallbackCodepage)
        {
            this.buffer = TextBuff.NewTextBuff(source, fallbackCodepage);
            this.lNum = 0;
            this.cNum = -1;
            this.chr = '\n'; // to initialize yyline, yycol and lineStart
            GetChr();
        }
#endif // !BYTEMODE
#endif // !NOFILES
        
        // ==============================================================

#if BABEL
        //
        //  Get the next token for Visual Studio
        //
        //  "state" is the inout mode variable that maintains scanner
        //  state between calls, using the EolState property. In principle,
        //  if the calls of EolState are costly set could be called once
        //  only per line, at the start; and get called only at the end
        //  of the line. This needs more infrastructure ...
        //
        public int GetNext(ref int state, out int start, out int end)
        {
            Tokens next;
            int s, e;
            s = state;        // state at start
            EolState = state;
            next = (Tokens)Scan();
            state = EolState;
            e = state;       // state at end;
            start = tokPos;
            end = tokEPos - 1; // end is the index of last char.
            return (int)next;
        }        
#endif // BABEL

        // ======== IScanner<> Implementation =========

        public override int yylex()
        {
            // parserMax is set by reflecting on the Tokens
            // enumeration.  If maxParseToken is defined
            // that is used, otherwise int.MaxValue is used.
            int next;
            do { next = Scan(); } while (next >= parserMax);
            return next;
        }
        
        int yyleng { get { return tokLen; } }
        int yypos { get { return tokPos; } }
        int yyline { get { return tokLin; } }
        int yycol { get { return tokCol; } }

        public string yytext
        {
            get 
            {
                if (tokTxt == null) 
                    tokTxt = buffer.GetString(tokPos, tokEPos);
                return tokTxt;
            }
        }

        void yyless(int n) { 
            buffer.Pos = tokPos;
            // Must read at least one char, so set before start.
            cNum = tokNum - 1; GetChr();
            // Now ensure that line counting is correct.
            lNum = tokLin;
            // And count the rest of the text.
            for (int i = 0; i < n; i++) GetChr();
            MarkEnd();
        }

        // ============ methods available in actions ==============

        internal int YY_START {
            get { return currentScOrd; }
            set { currentScOrd = value; 
                  currentStart = startState[value]; 
            } 
        }
        
        internal void BEGIN(int next) {
            currentScOrd = next;
            currentStart = startState[next];
        }

        // ============== The main tokenizer code =================

        int Scan()
        {
                for (; ; )
                {
                    int next;              // next state to enter                   
#if BACKUP
                    Result rslt = Result.noMatch;
#endif // BACKUP
#if LEFTANCHORS
                    for (;;)
                    {
                        // Discard characters that do not start any pattern.
                        // Must check the left anchor condition after *every* GetChr!
                        state = (lineStartNum == cNum ? anchorState[currentScOrd] : currentStart);
                        if ((next = NextState()) != goStart) 
                            break; // LOOP EXIT HERE...
                        GetChr();
                    }
                    
#else // !LEFTANCHORS
                    state = currentStart;
                    while ((next = NextState()) == goStart)
                        // At this point, the current character has no
                        // transition from the current state.  We discard 
                        // the "no-match" char.   In traditional LEX such 
                        // characters are echoed to the console.
                        GetChr();
#endif // LEFTANCHORS                    
                    // At last, a valid transition ...    
                    MarkToken();
                    state = next;
                    GetChr();
                    
                    while ((next = NextState()) > eofNum) // Exit for goStart AND for eofNum
#if BACKUP
                        if (state <= maxAccept && next > maxAccept) // need to prepare backup data
                        {
                            // ctx is an object. The fields may be 
                            // mutated by the call to Recurse2.
                            // On return the data in ctx is the
                            // *latest* accept state that was found.
                            Context ctx = new Context();
                            rslt = Recurse2(ctx, next);
                            if (rslt == Result.noMatch) 
                                RestoreStateAndPos(ctx);
                            break;
                        }
                        else
#endif // BACKUP
                        {
                            state = next;
                            GetChr();
                        }
                    if (state <= maxAccept) 
                    {
                        MarkEnd();
#region ActionSwitch
#pragma warning disable 162
    switch (state)
    {
        case eofNum:
            if (yywrap())
                return (int)Tokens.EOF;
            break;
        case 1:
{}
            break;
        case 2:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmSlash;
            break;
        case 3:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmAsterisk;
            break;
        case 4:
undefinedTokenError(yytext);
            break;
        case 5:
        case 6:
        case 7:
        case 8:
        case 9:
        case 10:
        case 11:
        case 12:
        case 13:
        case 14:
        case 73:
        case 75:
        case 76:
        case 77:
        case 79:
        case 80:
        case 81:
        case 83:
        case 84:
        case 85:
        case 86:
        case 88:
        case 89:
        case 90:
        case 91:
        case 92:
        case 93:
        case 95:
        case 96:
        case 99:
        case 100:
        case 101:
        case 102:
        case 103:
        case 104:
{
                          	yylval.ltrIdent=yytext;
							yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); 
                          	return (int)Tokens.lxmIdentifier;
                          }
            break;
        case 15:
{
							unquotedError(yytext);
						  }
            break;
        case 16:
        case 17:
{
                        	int r;
							try{
	                        	r=int.Parse(yytext);
							}catch(FormatException) {r=0; incorrectNumberFormat(yytext);}
                        	yylval.ltrNum=r;
							yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); 
                        	return (int)Tokens.lxmIntegerLiteral;
                          }
            break;
        case 18:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmDot;
            break;
        case 19:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmPlus;
            break;
        case 20:
        case 60:
        case 61:
{
							unquotedParameterError(yytext);
						  }
            break;
        case 21:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmAmpersand;
            break;
        case 22:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmEqual;
            break;
        case 23:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmMinus;
            break;
        case 24:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmGreater;
            break;
        case 25:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmCaret;
            break;
        case 26:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmColon;
            break;
        case 27:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmComma;
            break;
        case 28:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmExclamation;
            break;
        case 29:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmLeftBrace;
            break;
        case 30:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmLeftBracket;
            break;
        case 31:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmLeftParenth;
            break;
        case 32:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmLess;
            break;
        case 33:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmPercent;
            break;
        case 34:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmQuestion;
            break;
        case 35:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmRightBrace;
            break;
        case 36:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmRightBracket;
            break;
        case 37:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmRightParenth;
            break;
        case 38:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmSemicolon;
            break;
        case 39:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmTilde;
            break;
        case 40:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmVertical;
            break;
        case 41:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmVerticalEqual;
            break;
        case 42:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmVerticalVertical;
            break;
        case 43:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmPercentEqual;
            break;
        case 44:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmLessEqual;
            break;
        case 45:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmLessLess;
            break;
        case 46:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmLessLessEqual;
            break;
        case 47:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmNonEqual;
            break;
        case 48:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmColonColon;
            break;
        case 49:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmCaretEqual;
            break;
        case 50:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmGreaterEqual;
            break;
        case 51:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmGreaterGreater;
            break;
        case 52:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmGreaterGreaterEqual;
            break;
        case 53:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmMinusEqual;
            break;
        case 54:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmMinusMinus;
            break;
        case 55:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmArrow;
            break;
        case 56:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmArrowAsterisk;
            break;
        case 57:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmEqualEqual;
            break;
        case 58:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmAmpersandAmpersand;
            break;
        case 59:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmAmpersandEqual;
            break;
        case 62:
{
                          	yylval.ltrIdent=yytext.Substring(1, yytext.Length - 2);
							yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); 
                          	return (int)Tokens.lxmParamIdentifier;
                          }
            break;
        case 63:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmPlusPlus;
            break;
        case 64:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmPlusEqual;
            break;
        case 65:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmDotAsterisk;
            break;
        case 66:
        case 68:
        case 69:
{
                        	double dr;
							try{
								dr=double.Parse(yytext,System.Globalization.CultureInfo.InvariantCulture.NumberFormat);
							}catch(FormatException) {dr=0; incorrectNumberFormat(yytext);}
                        	yylval.ltrReal=dr;
							yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); 
                        	return (int)Tokens.lxmFloatingLiteral;
                          }
            break;
        case 67:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmDotDotDot;
            break;
        case 70:
{
                        	long r;
                        	r=atodec(yytext, 8);
                        	yylval.ltrNum=r;
							yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); 
                        	return (int)Tokens.lxmIntegerLiteral;
                          }
            break;
        case 71:
{
                        	long r;
                        	r=atodec(yytext, 16);
                        	yylval.ltrNum=r;
							yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); 
                        	return (int)Tokens.lxmIntegerLiteral;
                          }
            break;
        case 72:
{
                        	yylval.ltrString=yytext.Substring(1, yyleng-2);
							yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); 
                        	return (int)Tokens.lxmStringLiteral;
                          }
            break;
        case 74:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmVar;
            break;
        case 78:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmBreak;
            break;
        case 82:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmWhile;
            break;
        case 87:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmReturn;
            break;
        case 94:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmContinue;
            break;
        case 97:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmElse;
            break;
        case 98:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmDo;
            break;
        case 105:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmFunction;
            break;
        case 106:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmIf;
            break;
        case 107:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmAsteriskEqual;
            break;
        case 108:
        case 110:
{}
            break;
        case 109:
yylval.loc = new Location(tokLin, tokCol, tokELin, tokECol); return (int)Tokens.lxmSlashEqual;
            break;
        default:
            break;
    }
#pragma warning restore 162
#endregion
                    }
                }
        }

#if BACKUP
        Result Recurse2(Context ctx, int next)
        {
            // Assert: at entry "state" is an accept state AND
            //         NextState(state, chr) != goStart AND
            //         NextState(state, chr) is not an accept state.
            //
            SaveStateAndPos(ctx);
            state = next;
            // if (state == eofNum) return Result.accept;
            GetChr();

            while ((next = NextState()) > eofNum)
            {
                if (state <= maxAccept && next > maxAccept) // need to update backup data
                    SaveStateAndPos(ctx);
                state = next;
                if (state == eofNum) return Result.accept;
                GetChr(); 
            }
            return (state <= maxAccept ? Result.accept : Result.noMatch);
        }

        void SaveStateAndPos(Context ctx)
        {
            ctx.bPos  = buffer.Pos;
            ctx.cNum  = cNum;
            ctx.lNum  = lNum;
            ctx.state = state;
            ctx.cChr  = chr;
        }

        void RestoreStateAndPos(Context ctx)
        {
            buffer.Pos = ctx.bPos;
            cNum  = ctx.cNum;
            lNum  = ctx.lNum;
            state = ctx.state;
            chr   = ctx.cChr;
        }

        void RestorePos(Context ctx) { buffer.Pos = ctx.bPos; cNum = ctx.cNum; }
#endif // BACKUP

        // ============= End of the tokenizer code ================

#if STACK        
        internal void yy_clear_stack() { scStack.Clear(); }
        internal int yy_top_state() { return scStack.Peek(); }
        
        internal void yy_push_state(int state)
        {
            scStack.Push(currentScOrd);
            BEGIN(state);
        }
        
        internal void yy_pop_state()
        {
            // Protect against input errors that pop too far ...
            if (scStack.Count > 0) {
				int newSc = scStack.Pop();
				BEGIN(newSc);
            } // Otherwise leave stack unchanged.
        }
 #endif // STACK

        internal void ECHO() { Console.Out.Write(yytext); }
        
    } // end class Scanner
} // end namespace

// Guesser file for checking probable codepage of
// input files that do not have a unicode prefix.

//
//  This CSharp output file generated by Gardens Point LEX
//  Version:  1.0.0.240 (2008-11-01)
//  Machine:  ATTIC-1
//  DateTime: 28/10/2008 4:59:53 PM
//  UserName: john
//  GPLEX input file <guesser.lex>
//  GPLEX frame file <guesser.frame>
//
//  Option settings: noparser, minimize, classes, nocompressmap, nocompressnext
//

//
// Guesser.frame version 1.0.0 of 01-November-2008
//


namespace Guesser
{   
    public enum Tokens
    { 
      EOF = 0, maxParseToken = int.MaxValue 
    }

    public abstract class ScanBuff
    {
        public const int EOF = -1;
        public abstract int Pos { get; set; }
        public abstract int Read();
    }
        
    public class Scanner
    {
        ScanBuff buffer;
        
        enum Result {accept, noMatch, contextFound};
        
        bool yywrap() { return true; }
        
        public int GuessCodepage()
        {
            return Scan();
        }

        const int maxAccept = 10;
        const int initial = 0;
        const int eofNum = 0;
        const int goStart = -1;
        const int INITIAL = 0;

#region user code
/* 
 *  Reads the bytes of a file to determine if it is 
 *  UTF-8 or a single-byte codepage file.
 */
public long utfX = 0;
    public long uppr = 0;
#endregion user code

        int state;
        int currentStart = startState[0];
        int chr;
        
#region ScannerTables
  static int[] startState = {11, 0};

#region CharacterMap
    static sbyte[] map = new sbyte[256] {
/*     '\0' */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
/*   '\x10' */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
/*   '\x20' */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
/*      '0' */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
/*      '@' */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
/*      'P' */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
/*      '`' */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
/*      'p' */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
/*   '\x80' */ 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
/*   '\x90' */ 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
/*   '\xA0' */ 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
/*   '\xB0' */ 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
/*   '\xC0' */ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
/*   '\xD0' */ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
/*   '\xE0' */ 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
/*   '\xF0' */ 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5 };
#endregion

  static sbyte[][] nextState = new sbyte[12][];
  static Scanner() {
    nextState[0] = new sbyte[] {0, 0, 0, 0, 0, 0};
    nextState[1] = new sbyte[] {-1, -1, 10, -1, -1, -1};
    nextState[2] = new sbyte[] {-1, -1, -1, -1, -1, -1};
    nextState[3] = new sbyte[] {-1, -1, 8, -1, -1, -1};
    nextState[4] = new sbyte[] {-1, -1, 5, -1, -1, -1};
    nextState[5] = new sbyte[] {-1, -1, 6, -1, -1, -1};
    nextState[6] = new sbyte[] {-1, -1, 7, -1, -1, -1};
    nextState[7] = nextState[2];
    nextState[8] = new sbyte[] {-1, -1, 9, -1, -1, -1};
    nextState[9] = nextState[2];
    nextState[10] = nextState[2];
    nextState[11] = new sbyte[] {-1, 1, 2, 3, 4, 2};
}

int NextState() {
    if (chr == ScanBuff.EOF)
        return eofNum;
    else
        return nextState[state][map[chr]];
}

#endregion

        public class StreamBuff : ScanBuff
        {
            protected System.IO.BufferedStream bStrm;   // input buffer

            public StreamBuff(System.IO.Stream str) 
            { 
                this.bStrm = new System.IO.BufferedStream(str); 
            }

            public override int Read() { return bStrm.ReadByte(); }

            public override int Pos
            {
                get { return (int)bStrm.Position; }
                set { bStrm.Position = value; }
            }
        }

        public Scanner(System.IO.Stream file) { SetSource(file); }

        public void SetSource(System.IO.Stream source)
        {
            this.buffer = new StreamBuff(source);
            chr = buffer.Read();
        }

        int Scan()
        {
                for (; ; )
                {
                    int next;                   
                    state = currentStart;
                    while ((next = NextState()) == goStart)
                        chr = buffer.Read();
    
                    state = next;
                    chr = buffer.Read();
                    
                    while ((next = NextState()) > eofNum)
                    {
                        state = next;
                        chr = buffer.Read();
                    }
                    if (state <= maxAccept) 
                    {
#region ActionSwitch
#pragma warning disable 162
    switch (state)
    {
        case eofNum:
            switch (currentStart) {
                case 11:
if (utfX == 0 && uppr == 0) return -1; /* raw ascii */
                           else if (uppr * 10 > utfX) return 0;   /* default codepage */
                           else return 65001;                     /* UTF-8 encoding */
                    break;
            }
            if (yywrap())
                return (int)Tokens.EOF;
            break;
        case 1:
        case 2:
        case 3:
        case 4:
uppr++;
            break;
        case 5:
uppr += 2;
            break;
        case 6:
uppr += 3;
            break;
        case 7:
utfX += 3;
            break;
        case 8:
uppr += 2;
            break;
        case 9:
utfX += 2;
            break;
        case 10:
utfX++;
            break;
        default:
            break;
    }
#pragma warning restore 162
#endregion
                    }
                }
        }        
    } // end class Scanner
} // end namespace
