//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COTES.ISTOK.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COTES.ISTOK.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromDay_Month_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromDay_Month_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromDay_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromDay_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromDayWithBads_Month_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromDayWithBads_Month_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromDayWithBads_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromDayWithBads_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromDayWithSkips_Month_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromDayWithSkips_Month_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromDayWithSkips_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromDayWithSkips_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromHour_Day_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromHour_Day_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromHour_Month_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromHour_Month_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromHour_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromHour_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromHourWithBads_Day_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromHourWithBads_Day_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromHourWithBads_Month_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromHourWithBads_Month_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromHourWithBads_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromHourWithBads_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromHourWithSkips_Day_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromHourWithSkips_Day_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromHourWithSkips_Month_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromHourWithSkips_Month_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromHourWithSkips_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromHourWithSkips_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromMinute_Day_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromMinute_Day_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromMinute_Hour_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromMinute_Hour_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromMinute_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromMinute_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromMinuteWithBads_Day_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromMinuteWithBads_Day_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromMinuteWithBads_Hour_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromMinuteWithBads_Hour_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromMinuteWithBads_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromMinuteWithBads_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromMinuteWithSkips_Day_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromMinuteWithSkips_Day_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromMinuteWithSkips_Hour_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromMinuteWithSkips_Hour_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromMinuteWithSkips_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromMinuteWithSkips_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromRaw_Hour_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromRaw_Hour_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromRaw_Minute_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromRaw_Minute_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromRaw_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromRaw_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromRawWithBads_Hour_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromRawWithBads_Hour_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromRawWithBads_Minute_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromRawWithBads_Minute_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromRawWithBads_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromRawWithBads_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromSecond_Day_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromSecond_Day_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromSecond_Hour_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromSecond_Hour_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromSecond_Minute_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromSecond_Minute_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromSecond_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromSecond_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromSecondWithBads_Day_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromSecondWithBads_Day_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromSecondWithBads_Hour_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromSecondWithBads_Hour_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromSecondWithBads_Minute_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromSecondWithBads_Minute_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromSecondWithBads_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromSecondWithBads_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromSecondWithSkips_Day_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromSecondWithSkips_Day_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromSecondWithSkips_Hour_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromSecondWithSkips_Hour_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromSecondWithSkips_Minute_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromSecondWithSkips_Minute_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ValueAggregatorTests_FromSecondWithSkips_txt {
            get {
                object obj = ResourceManager.GetObject("ValueAggregatorTests_FromSecondWithSkips_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
