//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COTES.ISTOK.Block.Mirroring {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Query : global::System.Configuration.ApplicationSettingsBase {
        
        private static Query defaultInstance = ((Query)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Query())));
        
        public static Query Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ALTER DATABASE {0} SET PARTNER SUSPEND;\r\n")]
        public string Suspend {
            get {
                return ((string)(this["Suspend"]));
            }
            set {
                this["Suspend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ALTER DATABASE {0} SET PARTNER RESUME;\r\n")]
        public string Resume {
            get {
                return ((string)(this["Resume"]));
            }
            set {
                this["Resume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ALTER DATABASE {0} SET PARTNER FAILOVER;")]
        public string Switch {
            get {
                return ((string)(this["Switch"]));
            }
            set {
                this["Switch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ALTER DATABASE {0} SET PARTNER FORCE_SERVICE_ALLOW_DATA_LOSS;")]
        public string ForceSwitch {
            get {
                return ((string)(this["ForceSwitch"]));
            }
            set {
                this["ForceSwitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BACKUP DATABASE {0} TO DISK = \'{1}\';\r\n")]
        public string BackupDataBase {
            get {
                return ((string)(this["BackupDataBase"]));
            }
            set {
                this["BackupDataBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RESTORE DATABASE {0} FROM DISK = \'{1}\' WITH NORECOVERY;\r\n")]
        public string RestoreDataBase {
            get {
                return ((string)(this["RestoreDataBase"]));
            }
            set {
                this["RestoreDataBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CREATE ENDPOINT mirroring_endpoint STATE=STARTED AS TCP(LISTENER_PORT={0}) FOR DA" +
            "TABASE_MIRRORING( AUTHENTICATION=WINDOWS NEGOTIATE, ENCRYPTION=SUPPORTED, ROLE=P" +
            "ARTNER);\r\n")]
        public string CreateEndpoint {
            get {
                return ((string)(this["CreateEndpoint"]));
            }
            set {
                this["CreateEndpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ALTER DATABASE {0} SET PARTNER= N\'TCP://{1}:{2}\'\r\n")]
        public string SetPartner {
            get {
                return ((string)(this["SetPartner"]));
            }
            set {
                this["SetPartner"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BACKUP LOG {0} TO DISK = \'{1}\';\r\n")]
        public string BackupLog {
            get {
                return ((string)(this["BackupLog"]));
            }
            set {
                this["BackupLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RESTORE LOG {0} FROM DISK = \'{1}\' WITH NORECOVERY;\r\n")]
        public string RestoreLog {
            get {
                return ((string)(this["RestoreLog"]));
            }
            set {
                this["RestoreLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT sys.database_mirroring.mirroring_state_desc, sys.database_mirroring.mirroring_role_desc FROM sys.database_mirroring INNER JOIN sys.databases ON sys.database_mirroring.database_id = sys.databases.database_id AND sys.database_mirroring.mirroring_guid IS NOT NULL AND sys.databases.name = '{0}';")]
        public string StateQuery {
            get {
                return ((string)(this["StateQuery"]));
            }
            set {
                this["StateQuery"] = value;
            }
        }
    }
}
